version: '3'
services:

  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - --prometheus_endpoint=/docker-metrics
    ports:
      - 8080:8080

  node-exporter:
    image: prom/node-exporter:v0.17.0
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    command:
      - --web.telemetry-path=/node-metrics
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus:v2.5.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
      - node-exporter

  grafana:
    image: grafana/grafana:5.3.2
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  nginx:
    image: monitoring/nginx
    build: nginx
    container_name: nginx
    restart: always
    environment:
      - CERTBOT_EMAIL=sysadmin@savvydatainsights.co.uk
    volumes:
      - nginx_letsencrypt:/etc/letsencrypt
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana

volumes:
  grafana_data:
  nginx_letsencrypt: