---
- hosts: localhost
  gather_facts: no

  tasks:

  - name: Add TXT record in DNS for the ACME challenge
    azure_rm_dnsrecordset:
      resource_group: myResourceGroup
      relative_name: _acme-challenge.monitoring.savvydatainsights.co.uk
      zone_name: savvydatainsights.co.uk
      time_to_live: 60
      record_type: TXT
      state: present
      records:
        - entry: "{{ 'monitoring.savvydatainsights.co.uk' | hash('sha1') }}"

- hosts: localhost
  gather_facts: no

  tasks:

  - name: Remove the ACME challenge's TXT record from DNS
    azure_rm_dnsrecordset:
      resource_group: myResourceGroup
      relative_name: _acme-challenge.monitoring.savvydatainsights.co.uk
      zone_name: savvydatainsights.co.uk
      record_type: TXT
      state: absent