---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: false

  tasks:
    - name: Add the Prometheus target that aggregates jmx_exporters metrics
      include_tasks: add-exporter.yml
      vars:
        exporter: jvms
