---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: false

  tasks:
    - name: Add the cAdvisor target file
      include_tasks: add-exporter.yml
      vars:
        exporter: cadvisor
