---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - prom_conf_file: "{{ prom_conf_file_arg | default('prometheus.yml' | realpath) }}"
    - prom_url: "{{ prom_url_arg | default('http://localhost:9090') }}"
  tasks:
    - name: Check if the Prometheus configuration file exists
      stat:
        path: "{{ prom_conf_file }}"
      register: prom_conf_file_check
    - name: Assert that the Prometheus configuration file exists
      assert:
        that: prom_conf_file_check.stat.exists and prom_conf_file_check.stat.isreg
        msg: "Invalid Prometheus configuration file."
    - name: Check if Prometheus is reachable
      uri:
        url: "{{ prom_url }}"
      ignore_errors: yes
      register: prom_url_check
    - name: Assert Prometheus availability
      assert:
        that: prom_url_check.status == 200
        msg: "Unfortunately Prometheus is unreachable"
