---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: false

  vars:
    - _host: "{{ host | default('localhost') }}"
    - _target: "{{ target | default('cadvisor:8080') }}"

  tasks:
    - name: Add the cAdvisor target file
      template:
        src: templates/tg_.j2
        dest: "{{ '..' if inventory_hostname == '127.0.0.1' else '.' }}/prometheus/tg_cadvisor_{{ _host }}.yml"
