---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: no

  vars:
    - _host: "{{ host | default('localhost') }}"
    - _target: "{{ target | default('node-exporter:9100') }}"

  tasks:
    - name: Add the node-exporter target file
      template:
        src: templates/tg_.j2
        dest: "{{ '..' if inventory_hostname == '127.0.0.1' else '.' }}/prometheus/tg_node_{{ _host }}.yml"
