---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: no

  vars:
    - cadvisor_host: "{{ host | default('localhost') }}"
    - cadvisor_target: "{{ target | default('cadvisor:8080') }}"

  tasks:
    - name: Add the cAdvisor target file
      template:
        src: templates/tg_cadvisor.j2
        dest: "../prometheus/tg_cadvisor_{{ cadvisor_host }}.yml"
