---
monitoring:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
    production:
      ansible_host: 100.0.0.4
      ansible_user: sdiadmin
      ansible_ssh_private_key_file: ~/.ssh/savvy_azure_key
      ansible_python_interpreter: python3
