---
- hosts: default
  gather_facts: false

  vars:
    mon_domain: monitoring.savvydatainsights.co.uk
    cert_dir: nginx/letsencrypt/{{ mon_domain }}

  vars_files:
    - azure_credentials.yml

  tasks:
    - name: Check if acme.sh is installed
      stat:
        path: ~/.acme.sh
      register: acme_path

    - name: Install acme.sh
      block:
        - name: Clone acme.sh
          git:
            repo: https://github.com/Neilpang/acme.sh.git
            dest: /tmp/acme.sh
            version: 2.7.9
        - name: Install acme.sh
          shell: ./acme.sh --install
          args:
            chdir: /tmp/acme.sh
      when: not acme_path.stat.exists

    - name: Copy required files
      copy:
        src: "../{{ item }}"
        dest: .
      loop:
        - docker-compose.yml
        - nginx
        - grafana
        - prometheus

    - name: Check if privkey.pem is generated
      stat:
        path: "{{ cert_dir }}/privkey.pem"
      register: privkey_path

    - name: Generate the certificate
      block:
        - name: Generate the certificate
          shell: ~/.acme.sh/acme.sh --issue --dns dns_azure --dnssleep 10 --force -d {{ mon_domain }} --staging
          environment: "{{ azure_credentials }}"
        - name: Install the certificate
          shell: ~/.acme.sh/acme.sh --install-cert -d {{ mon_domain }} --fullchain-file {{ cert_dir }}/fullchain.pem --key-file {{ cert_dir }}/privkey.pem
        - name: Create a cron file
          cron:
            name: "renew certificate"
            minute: 0
            hour: 0
            user: "{{ ansible_user }}"
            job: "~/.acme.sh/acme.sh --cron > /dev/null"
            cron_file: renew-certificate
          become: true
      when: not privkey_path.stat.exists

    - name: Set up the Docker services
      docker_service:
        project_name: monitoring
        project_src: .
        state: present
      become: true
