---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: no

  vars:
    - _host: "{{ host | default('localhost') }}"

  tasks:
    - name: Remove the cAdvisor target file
      file:
        path: "{{ '..' if inventory_hostname == '127.0.0.1' else '.' }}/prometheus/tg_cadvisor_{{ _host }}.yml"
        state: absent
