---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: false

  tasks:
    - name: Remove the node-exporter target file
      include_tasks: rm-exporter.yml
      vars:
        exporter: node
