---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: false

  vars:
    - _host: "{{ host | default('localhost') }}"

  tasks:
    - name: Remove the node-exporter target file
      file:
        path: "{{ '..' if inventory_hostname == 'localhost' else '.' }}/prometheus/tg_node_{{ _host }}.yml"
        state: absent
