---
- hosts: "{{ prometheus_host | default('localhost') }}"
  gather_facts: false

  tasks:
    - name: Remove the postgres_exporter target file
      include_tasks: rm-exporter.yml
      vars:
        exporter: postgres
