---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - prom_conf_file: "{{ prom_conf_file_arg | default('prometheus.yml' | realpath) }}"
    - prom_url: "{{ prom_url_arg | default('http://localhost:9090') }}"
    - job_name: "{{ job_name_arg | default('localhost') }}"
    - target: "{{ target_arg | default('cadvisor:8080') }}"
  tasks:
    - name: Check Prometheus variables
      import_tasks: prometheus-assertions.yml
    - name: Remove the target configuration
      blockinfile:
        path: "{{ prom_conf_file }}"
        marker: "# {mark} {{ job_name }} configuration"
        block: "{{ lookup('template', 'target-conf-template.j2') }}"
        state: absent
      register: blockinfile_result
    - name: Reload Prometheus
      uri:
        url: "{{ prom_url }}/-/reload"
        method: POST
      when: blockinfile_result.changed
